baseurl = "https://blog.ngcrl.org"
languageCode = "en-us"
title = "Burgess' Blog"

theme = "paper"

hasCJKLanguage = true

[params.author]
    name = "Burgess Chang"

[params]
    description = "Programming, Emacs, Linux."

[[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
